# Generated by Django 3.2.3 on 2021-05-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('message', models.TextField(default='', max_length=1000)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='chat_list',
            fields=[
                ('chat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('second_user_id', models.IntegerField()),
            ],
        ),
    ]
