# Generated by Django 3.2.3 on 2021-05-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_list',
            name='second_user_want',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat_list',
            name='user_want',
            field=models.BooleanField(default=False),
        ),
    ]
