# Generated by Django 3.2 on 2021-05-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210524_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_list',
            name='chat_id',
        ),
        migrations.AddField(
            model_name='chat_list',
            name='user_id',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='chat_list',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
